<?php
/**
 * System settings shipped with the modxMCP package (namespace "modxmcp").
 *
 * @var modX $modx
 * Returns an array of modSystemSetting objects keyed by setting key.
 *
 * Security defaults: the component is DISABLED on install (modxmcp.enabled = No)
 * and the api_token is generated by resolve.token.php. Filesystem root browsing is off.
 */
/* @var modX $modx */
$settings = array();

$defs = array(
    // key, value, xtype, area
    array('modxmcp.enabled', 0, 'combo-boolean', 'modxmcp:main'),
    array('modxmcp.api_token', '', 'text-password', 'modxmcp:main'),
    array('modxmcp.service_user_id', 1, 'textfield', 'modxmcp:main'),
    array('modxmcp.audit_log', 1, 'combo-boolean', 'modxmcp:main'),
    array('modxmcp.debug', 0, 'combo-boolean', 'modxmcp:main'),
    array('modxmcp.auto_static', 0, 'combo-boolean', 'modxmcp:main'),
    array('modxmcp.allow_package_install', 0, 'combo-boolean', 'modxmcp:security'),
    array('modxmcp.allow_run_processor', 0, 'combo-boolean', 'modxmcp:security'),
    array('modxmcp.max_payload_bytes', 1048576, 'textfield', 'modxmcp:limits'),
    array('modxmcp.allow_root_filesystem_read', 0, 'combo-boolean', 'modxmcp:security'),
    array('modxmcp.component_code_roots', 'core/components,assets/components', 'textfield', 'modxmcp:security'),
    array('modxmcp.core_path', '{core_path}components/modxmcp/', 'textfield', 'modxmcp:paths'),
);

foreach ($defs as $d) {
    /* @var modSystemSetting $setting */
    $setting = $modx->newObject('modSystemSetting');
    $setting->fromArray(array(
        'key' => $d[0],
        'value' => $d[1],
        'xtype' => $d[2],
        'namespace' => 'modxmcp',
        'area' => $d[3],
    ), '', true, true);
    $settings[$d[0]] = $setting;
}

unset($defs, $d);
return $settings;
